name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 4. Build & push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/devops-portfolio-app:latest .
          docker push ghcr.io/${{ github.repository_owner }}/devops-portfolio-app:latest

      # 5. Deploy to Kubernetes
      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.9'

      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
