apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: api-app
        image: ghcr.io/ryanhaylo88/python-api-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_VERSION
          value: "v1"